name: MooTools Table Sorter
author: cnizzdotcom
category: Widgets
tags: [table sorter, sorting]
demo: http://cnizz.com/mootools/table-sorter/
doc: http://blog.cnizz.com/tag/mootools-table-sorter/
current: 0.9.5
